### ISSUE TITLE
wg-ux video from last meeting

### ISSUE THREAD

**Issue by tobilg** [dcos/community#2]
Hi!

Just a question, will the wg-ux video from the last meeting be uploaded as well?

Thanks,
Tobi

**Comment by asridharan** [comment]
@judithpatudith ^^

**Comment by judithpatudith** [comment]
Thanks for the reminder @tobilg and @asridharan! Guess I need to turn on issue notifications for this repo...
[Recording Here](https://www.youtube.com/watch?v=0ZQQ6ezW1oQ&list=PLVWqoBEzghqcR8xrc1jHr3Fh12yqXS67a)
